#release configuration
#Fri Oct 03 17:11:02 MSK 2025
completedPhase=check-poms
exec.pomFileName=pom.xml
exec.snapshotReleasePluginAllowed=false
preparationGoals=clean verify
project.scm.com.dmdev\:database.connection=scm\:git\:git@github.com\:Dombaeva/first-maven.git
project.scm.com.dmdev\:database.developerConnection=scm\:git\:git@github.com\:Dombaeva/first-maven.git
project.scm.com.dmdev\:database.tag=HEAD
project.scm.com.dmdev\:database.url=https\://github.com/Dombaeva/first-maven
project.scm.com.dmdev\:first-maven.connection=scm\:git\:git@github.com\:Dombaeva/first-maven.git
project.scm.com.dmdev\:first-maven.developerConnection=scm\:git\:git@github.com\:Dombaeva/first-maven.git
project.scm.com.dmdev\:first-maven.tag=HEAD
project.scm.com.dmdev\:first-maven.url=https\://github.com/Dombaeva/first-maven
project.scm.com.dmdev\:service.connection=scm\:git\:git@github.com\:Dombaeva/first-maven.git
project.scm.com.dmdev\:service.developerConnection=scm\:git\:git@github.com\:Dombaeva/first-maven.git
project.scm.com.dmdev\:service.tag=HEAD
project.scm.com.dmdev\:service.url=https\://github.com/Dombaeva/first-maven
project.scm.com.dmdev\:web.connection=scm\:git\:git@github.com\:Dombaeva/first-maven.git
project.scm.com.dmdev\:web.developerConnection=scm\:git\:git@github.com\:Dombaeva/first-maven.git
project.scm.com.dmdev\:web.tag=HEAD
project.scm.com.dmdev\:web.url=https\://github.com/Dombaeva/first-maven
projectVersionPolicyId=default
pushChanges=true
releaseStrategyId=default
remoteTagging=true
scm.branchCommitComment=@{prefix} prepare branch @{releaseLabel}
scm.commentPrefix=[maven-release-plugin] 
scm.developmentCommitComment=@{prefix} prepare for next development iteration
scm.releaseCommitComment=@{prefix} prepare release @{releaseLabel}
scm.rollbackCommitComment=@{prefix} rollback the release of @{releaseLabel}
scm.tagNameFormat=@{project.artifactId}-@{project.version}
scm.url=scm\:git\:git@github.com\:Dombaeva/first-maven.git
